### ISSUE TITLE
Is README.md for new backend system correct or?

### ISSUE THREAD

**Issue by SmajlovicA** [tduniec/backstage-template-reporting-plugin#2]
Hi

I am trying to use your template reporting plugin, I have a new backend system and have some issues with installing it.

Basically, I am following README.md file doing this:

// From your Backstage root directory
yarn add --cwd packages/backend @tduniec/backstage-plugin-template-reporting-backend

// Wire up the plugin in Backstage new backend system in packages/backend/src/index.ts
backend.add(import('@tduniec/backstage-plugin-template-reporting-backend'));

// And that in app-config.yaml:
backend:
  auth:
    externalAccess:
      - type: static
        options:
          token: ${MY_TOKEN}
          subject: scaffolder-access-for-template-reporting # should be this subject value configured

// rest I can use defaults that are there.

Is there anything else required in the backend? Frontend is okay, I have no issue adding but of course, there are no reports and I can't find this template-reporting scaffolder action.

Thank you

**Comment by SmajlovicA** [comment]
Hi @toma2395 

Thank you so much for your quick reply. 

I tried to do this by adding the code below in the same file:
packages/backend/src/index.ts 

```js
const scaffolderModuleCustomExtensions = createBackendModule({
  pluginId: 'scaffolder', // name of the plugin that the module is targeting
  moduleId: 'custom-extensions',
  register(env) {
    env.registerInit({
      deps: {
        scaffolder: scaffolderActionsExtensionPoint,
        config: coreServices.rootConfig,
        // ... and other dependencies as needed
      },
      async init({ scaffolder, config /* ..., other dependencies */ }) {
        scaffolder.addActions(generateTemplateReport(config));
      },
    });
  },
});
backend.add(scaffolderModuleCustomExtensions());
```

And after that I received these are missing in the editor:
- scaffolderActionsExtensionPoint
- coreServices
- scaffolder
- generateTemplateReport

I am not sure what are next steps after completing the steps mentioned in the first post.

Thank you

**Comment by SmajlovicA** [comment]
Hi @toma2395 

Just to let you know that I manage to work, I have reports now.

Basicaly I added these inports.

```js
import {
  TemplateReportObj,
  templateReportingReportsExtensionPoint,
  generateTemplateReport,
} from '@tduniec/backstage-plugin-template-reporting-backend';
import { coreServices } from '@backstage/backend-plugin-api';
import { scaffolderActionsExtensionPoint } from '@backstage/plugin-scaffolder-node/alpha';
```

Is there anything here to add or change because you left some comments:

```js
const scaffolderModuleCustomExtensions = createBackendModule({
  pluginId: 'scaffolder', // name of the plugin that the module is targeting
  moduleId: 'custom-extensions',
  register(env) {
    env.registerInit({
      deps: {
        scaffolder: scaffolderActionsExtensionPoint,
        config: coreServices.rootConfig,
        // ... and other dependencies as needed
      },
      async init({ scaffolder, config /* ..., other dependencies */ }) {
        scaffolder.addActions(generateTemplateReport(config));
      },
    });
  },
});
backend.add(scaffolderModuleCustomExtensions());
```

Also on the right corner is saying Owner: Rackspace, is that possible to change?


Thank you

**Comment by tduniec** [comment]
Cool, I will add these to the instructions, it was missed. 

I am pleased that it is working for you! 

Maybe I will remove this label in future releases. Please keep updated :) 

Let me know your feedback about this plugin since I have not requested to publish it on the official community yet and you may be one of first users :)
